---
title: Content

columns:
  main:
    width: 2/3
    sections:
      editor:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      authorship:
        type: fields
        fields:
          author:
            type: users
            default: true
            disabled: true
          coauthor:
            type: users
            label: Co-Authors
            multiple: true
      files:
        type: files
