---
title: Content

columns:
  main:
    width: 2/3
    sections:
      editor:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      authorship:
        type: fields
        fields:
          author:
            type: users
            default: true
            disabled: true
          coauthor:
            type: users
            label: Co-Authors
            help: "Add co-authors to <strong>{{ page.title.short(30) }}</strong> to grant them editing access. You can search for names or email addresses."
            info: "{{ user.email }}"
            limit: 10
            link: false
            multiple: true
            query: kirby.users.filterBy("role", "LdapUser").not(kirby.user)
            search: true
      date:
        type: fields
        fields:
          date:
            type: structure
            title: Date & Time
            columns:
              date:
                mobile: true
              time:
                mobile: true
            fields:
              date:
                type: date
                help: "The date and time of the event."
                default: "2025-07-18"
                min: "2025-07-18"
                max: "2025-07-20"
              time:
                type: time
                help: "The date and time of the event."
                default: "13:00"
                min: "10:00"
                max: "23:59"
      files:
        type: files
