---
title: Content

columns:
  main:
    width: 2/3
    sections:
      editor:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      authorship:
        type: fields
        fields:
          author:
            type: users
            default: true
            disabled: true
          coauthor:
            type: users
            label: Co-Authors
            help: "Add co-authors to <strong>{{ page.title.short(30) }}</strong> to grant access (for editing) to this project. You can search for names or email addresses."
            info: "{{ user.email }}"
            limit: 10
            link: false
            multiple: true
            query: kirby.users.filterBy("role", "LdapUser").not(kirby.user)
            search: true
      files:
        type: files
