title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
          author:
            type: users
            default: true
            disabled: true
          coauthor:
            type: users
            label: Co-Authors
            multiple: true
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

